version: "3.8"
services:
  spa:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - "server:go-server"
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
