# Multi-stage build
FROM golang:1.15 AS goBuilder
ADD ./main.go main.go
ADD ./server server
# Fetch Go dependencies
RUN go get -d -v
RUN CGO_ENABLED=0 GOOS=linux go build -o /go-react-boilerplate -a -tags netgo -ldflags '-s -w' .

FROM scratch
WORKDIR /app
COPY --from=goBuilder /go-react-boilerplate /app/go-react-boilerplate
EXPOSE 3001
ENTRYPOINT ["/app/go-react-boilerplate", "-env=dev", "-port=3001"]
