version: "3.8"
services:
  spa:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - "server:go-server"
    # volumes:
    #   - './client:/app'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
