apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-react-boilerplate
  # namespace: go-react-app
spec:
  selector:
    matchLabels:
      app: go-react-boilerplate
  replicas: 2
  template:
    metadata:
      labels:
        app: go-react-boilerplate
    spec:
      containers:
      - name: go-react-boilerplate
        imagePullPolicy: Always
        # $ARGOCD_APP_REVISION is a default environment variable in Argo CD
        image: danielhoward314/go-react-boilerplate:$ARGOCD_APP_REVISION
        ports:
          # Should match the port number that the Go application listens on
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: go-react-app
  # annotations:
  #   external-dns.alpha.kubernetes.io: domain.com
spec:
  type: NodePort
  ports:
  - name: http
    port: 9000
    # port is what you'll type into browser, targetPort and containerPort should match
    targetPort: 3001
  selector:
    app: go-react-app
